### ISSUE TITLE
Manual Activation/Trigger Button not functional to activate goal light and horn

### ISSUE THREAD

**Issue by pbouthil** [insaneway/nhl_goal_light_2023_api#1]
I have implemented your adaptation of the NHL Goal Light from https://github.com/arim215/nhl_goal_light. It looks like all was working. When I ran the script in terminal it prompted to enter the team and delay. All seemed to be good. I then went to the manual trigger button on my goal light box to see if my goal horn would work and the program error-ed out. I looked to see if any of the connections had changed but i saw no changes. It this something that you are also working on?

2nd I noticed that on your Github page you are having us clone the original code and not your new modified code.

**Comment by insaneway** [comment]
I noticed that I forgot to change the clone command to the modified code. That has been fixed.

The button I overlooked because I don't have one. I'll work on fixing it. I believe it doesn't work because of how I modified the function to accept the team tricode it is setup with. For now it will only go off based on the API.

**Comment by pbouthil** [comment]
Thank you for the quick response and explanation. I look forward to your continued work on this project. I have a button so I can show and tell the light and horn for family, friends and guests.

**Comment by insaneway** [comment]
Button issue should be fixed. I don't have a physical button, but I simulated the activation of GPIO 11 and it worked. Also added a 30 sec limit to the music and a fader. All documented in the new readme.

**Comment by pbouthil** [comment]
The button works perfectly. All is fully functional. Thanks for taking to time to get this NHL Goal Light up and running again.

**Comment by pbouthil** [comment]
![20210312_113844 (s)](https://github.com/insaneway/nhl_goal_light_2023_api/assets/5903893/964b8498-2187-4133-84c5-3042875be13d)
